### ISSUE TITLE
[feeture request] Big Text using blittle

### ISSUE THREAD

**Issue by hugeblank** [LDDestroier/enchat#4]
I mean you already have /picto for making cool images, naturally the next step is text, no? You could either make this a command, using something like say `/big`, or add another colorcode, `&b` being for bold. I suggest investigating Wojbie's bigfont for the text rendering if you aren't going to do it in-house.

**Comment by LDDestroier** [comment]
This is possible... I could make my own 6x6 custom font in pain and put that in.
I'd really really need to adjust notifications in addition, as they scroll in a different direction.
